version: "3.8"

volumes:
  ORM_database:

services:
  api:
    container_name: server_part
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    container_name: psql_db
    image: postgres:latest
    volumes:
      - v_psql_db:./ff/
    environment:
      - POSTGRES_PASSWORD=PetRigi1504
    ports:
      - 5432:8080
