version: "3.8"

services:
  api:
    build: .
#    command: ./wait-for-postgres.sh database
    command: ./wait-for-postgres.sh database python main.py
#    container_name: server_part
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - DB_PASSWORD=PetRigi1504

  database:
    restart: always
#    container_name: psql_db
    image: postgres:latest
#    volumes:
#      - v_psql_db:/usr/scr/database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PetRigi1504
      - POSTGRES_DB=coursework