version: "3.8"

volumes:
  database_volume:
  storage_volume:

services:
  app:
    build: .
    command: ./wait-for-postgres.sh database python main.py
    container_name: app_container
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - database
    env_file:
      - ./.env
    volumes:
      - storage_volume:/data/storage
    restart: always

  database:
    container_name: database_container
    image: postgres:latest
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PetRigi1504
      - POSTGRES_DB=coursework
    restart: always