version: "3.8"

services:
  app:
    build: .
    command: ./wait-for-postgres.sh database python main.py
    container_name: app_container
    ports:
      - 8080:8080
    depends_on:
      - database
    env_file:
      - ./.env
#    environment:
#      - DB_PASSWORD=PetRigi1504
    restart: always

  database:
    container_name: database_container
    image: postgres:latest
#    volumes:
#      - v_psql_db:/usr/scr/database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PetRigi1504
      - POSTGRES_DB=coursework
    restart: always